[
    uuid( 2221FC82-6A3B-378D-656C-019B31C40E4B )
]
library TestLib
{
    importlib("stdole2.tlb");


    interface Foo;

    interface IAllocator;



    [
        object,
        uuid( 4CB2A593-C19F-320B-62B2-03ED6A7C33F0 ),
        nonextensible,
        pointer_default(unique)
    ]
    interface Foo : IUnknown
    {
        [id(0)]
        uint32 Method([in] uint32 a);
    
    }

    [
        object,
        uuid( 18EE22B3-B0C6-44A5-A94A-7A417676FB66 ),
        nonextensible,
        pointer_default(unique)
    ]
    interface IAllocator : IUnknown
    {
        [id(0)]
        BSTR AllocBstr([in] BSTR text, [in] uint32 len);
    
        [id(1)]
        void FreeBstr([in] BSTR bstr);
    
        [id(2)]
        void* Alloc([in] size_t len);
    
        [id(3)]
        void Free([in] void* ptr);
    
    }



    [
        uuid( DF3C35C1-CDD2-3B15-6A24-A7E9D6B3DDF0 )
    ]
    coclass Allocator
    {
    
        interface IAllocator;
    }

}
